version: '3'

services:

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data:/data
